services:
   - type: web
     name: ipdims-server
     runtime: node
     rootDir: server
     buildCommand: npm install
     startCommand: npm start
     healthCheckPath: /health
     envVars:
        - key: NODE_VERSION
          value: 20
        - key: MONGODB_URI
          sync: false
        - key: JWT_SECRET
          generateValue: true
        - key: ADMIN_EMAIL
          sync: false
        - key: ADMIN_PASSWORD
          sync: false
        - key: CLOUDINARY_NAME
          sync: false
        - key: CLOUDINARY_API_KEY
          sync: false
        - key: CLOUDINARY_SECRET_KEY
          sync: false
        - key: EMAIL_HOST
          sync: false
        - key: EMAIL_PORT
          value: "587"
        - key: EMAIL_USER
          sync: false
        - key: EMAIL_PASS
          sync: false
        - key: CLIENT_URL
          sync: false
        - key: ADMIN_URL
          sync: false

   - type: web
     name: ipdims-client
     runtime: node
     rootDir: client
     buildCommand: npm install && npm run build
     startCommand: npm run preview
     env: static
     staticPublishPath: dist
     envVars:
        - key: NODE_VERSION
          value: 20
        - key: VITE_BACKEND_URL
          sync: false

   - type: web
     name: ipdims-admin
     runtime: node
     rootDir: admin
     buildCommand: npm install && npm run build
     startCommand: npm run preview
     env: static
     staticPublishPath: dist
     envVars:
        - key: NODE_VERSION
          value: 20
        - key: VITE_BACKEND_URL
          sync: false
        - key: VITE_CLIENT_URL
          sync: false
